import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link';

export default function movieItem({info}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Filme: {info.title}
        </h1>

        <p>{info.overview}</p>

        <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width="1250" />

        <Link href='/busca/'> ir para busca </Link>


      </main>

 
    </div>
  )
}


export async function getServerSideProps(context){

  const res = await fetch(`${process.env.mypageurl}/api/movies/${context.params.id}`);
  const json = await res.json();

//   console.log(json)
//   console.log('etc')

  return{
    props: {
      info: json.info
    }
  }
}