import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home({list}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Filmes em Destaque:
        </h1>

        <Link href='/busca/'> ir para busca </Link>

     <ul>
      {list.map(item =>(
        <li>
          <Link href={`/movies/${item.id}`}>
          <img src={`https://image.tmdb.org/t/p/original${item.poster_path}`} width='150'/><br/>  
          {item.title}
          </Link>     
        </li>
      ))}
     </ul>
    <Link href="/sobre">Sobre</Link>
      </main>

 
    </div>
  )
}


export async function getServerSideProps(){
  const res = await fetch(`${process.env.NEXT_PUBLIC_mypageurl}/api/trending`);
  const resp = await res.json();

  return{
    props: {
      list: resp.list
    }
  }
}