import Head from "next/head";

export default function Sobre({autor}){
    return(
<>
       <Head>
        <title>Create Next App!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h4>sobre</h4>
      <h3>Autor:{autor}</h3>


      </>
    )
}

export async function getStaticProps(){
    return {
        props: {
            autor: "Johnny"
        }
    }

}